const words={3:["IBU","AYU","API","BOL","TAS","JAM"],4:["BUKU","BOLA","MEJA","SAPI","KAKI","MATA","ROTI","BAJU","TOPI"],5:["MOBIL","RUMAH","KURSI","PAPAN","BOTOL"],6:["SEPATU","KELAPA","KAMERA"]};
let len=4,last=-1,speaking=false;
const $=id=>document.getElementById(id),word=$("word"),reading=$("reading"),hint=$("hint");
function pool(){return(words[len]||words[4]).filter(w=>w.length===len)}
function next(){const p=pool();if(!p.length)return;let i;do{i=Math.floor(Math.random()*p.length)}while(p.length>1&&i===last);last=i;word.textContent=p[i];reading.textContent=""}
const letterSound={A:"a",B:"bé",C:"cé",D:"dé",E:"é",F:"éf",G:"gé",H:"ha",I:"i",J:"jé",K:"ka",L:"él",M:"ém",N:"én",O:"o",P:"pé",Q:"ki",R:"ér",S:"és",T:"té",U:"u",V:"vé",W:"wé",X:"éks",Y:"yé",Z:"zét"};
function syllables(w){const map={BUKU:["BU","KU"],TOPI:["TO","PI"],BOLA:["BO","LA"],MEJA:["ME","JA"],SAPI:["SA","PI"],KAKI:["KA","KI"],MATA:["MA","TA"],ROTI:["RO","TI"],BAJU:["BA","JU"],MOBIL:["MO","BIL"],RUMAH:["RU","MAH"],KURSI:["KUR","SI"],PAPAN:["PA","PAN"],BOTOL:["BO","TOL"],SEPATU:["SE","PA","TU"],KELAPA:["KE","LA","PA"],KAMERA:["KA","ME","RA"]};return map[w]||[w]}
function parts(w){const out=[];for(const s of syllables(w)){for(const c of s)out.push({show:c,speak:letterSound[c]||c});out.push({show:s,speak:s})}out.push({show:w,speak:w});return out}
function phrase(w){return parts(w).map(x=>x.speak).join(". ")+"."}
async function playPhrase(w){const r=await fetch("/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",body:JSON.stringify({text:phrase(w)})});if(!r.ok){let d="";try{d=await r.text()}catch(e){}throw new Error("TTS "+r.status+" "+d)}const url=URL.createObjectURL(await r.blob()),a=new Audio(url);return {a,url}}
function fallback(w){return new Promise(resolve=>{const u=new SpeechSynthesisUtterance(phrase(w));u.lang="id-ID";u.rate=.62;u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u)})}
async function read(){if(speaking)return;speaking=true;const w=word.textContent,seq=parts(w);try{let audio;try{audio=await playPhrase(w)}catch(e){const m=String(e?.message||e);const match=m.match(/TTS\s+(\d{3})/);const code=match?match[1]:"NO STATUS";reading.textContent="ANJANI ERROR "+code;console.error(e);await new Promise(r=>setTimeout(r,6000));return}
if(audio){const total=Math.max(2200,seq.length*650);audio.a.play();const start=Date.now();for(let i=0;i<seq.length;i++){reading.textContent=seq[i].show;const target=(i+1)*total/seq.length;const wait=Math.max(180,target-(Date.now()-start));await new Promise(r=>setTimeout(r,wait))}await new Promise(r=>{if(audio.a.ended)return r();audio.a.onended=r;audio.a.onerror=r});URL.revokeObjectURL(audio.url)}
}finally{speaking=false;setTimeout(()=>reading.textContent="",650)}}
$("next").addEventListener("click",next);$("speak").addEventListener("click",read);$("settings").addEventListener("click",()=>$("sheet").classList.add("show"));$("close").addEventListener("click",()=>$("sheet").classList.remove("show"));$("length").addEventListener("change",e=>{len=Number(e.target.value);hint.textContent=len+" huruf";last=-1;next();$("sheet").classList.remove("show")});